services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - merns-shop-mongo:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  merns-shop-mongo:
